### ISSUE TITLE
Not everything is dark

### ISSUE THREAD

**Issue by marton200472** [ZD4ve/DarkPorta#1]
Fix pls

![image](https://github.com/ZD4ve/DarkPorta/assets/68277582/40f089a6-60e6-4a86-890c-cef98bfb1414)
![image](https://github.com/ZD4ve/DarkPorta/assets/68277582/ad4b211c-2e65-492a-bdf1-b7aacfdc9851)

Very nice project btw

**Comment by ZD4ve** [comment]
Fixed in 1.1 update.
